"Resource/UI/WinPanel_Base.res"
{
	"TeamScoresPanel"
	{
		"ControlName"								"EditablePanel"
		"FieldName"									"TeamScoresPanel"
		"XPos"										"-41"
		"YPos"										"13"
		"Wide"										"480"
		"Tall"										"60"
		"Visible"									"1"

		"BlueScoreBG"
		{
			"ControlName"							"EditablePanel"
			"FieldName"								"BlueScoreBG"
			"XPos"									"50"
			"YPos"									"15"
			"Wide"									"135"
			"Tall"									"40"
			"Visible"								"1"
			"Enabled"								"1"
		}
		"RedScoreBG"
		{
			"ControlName"							"EditablePanel"
			"FieldName"								"RedScoreBG"
			"XPos"									"197"
			"YPos"									"15"
			"Wide"									"135"
			"Tall"									"40"
			"Visible"								"1"
			"Enabled"								"1"
		}
		"BlueTeamLabel"
		{
			"ControlName"							"CExLabel"
			"FieldName"								"BlueTeamLabel"
			"Font"									"m0refont11"
			"LabelText"								"%blueteamname%"
			"TextAlignment"							"west"
			"XPos"									"56"
			"YPos"									"25"
			"ZPos"									"10"
			"Wide"									"100"
			"Tall"									"20"
			"Visible"								"1"
			"Enabled"								"1"
			"FGColor"								"TanLight"
		}
		"BlueTeamScore"
		{
			"ControlName"							"CExLabel"
			"FieldName"								"BlueTeamScore"
			"Font"									"m0refont36"
			"LabelText"								"%blueteamscore%"
			"TextAlignment"							"east"
			"XPos"									"80"
			"YPos"									"0"
			"ZPos"									"3"
			"Wide"									"100"
			"Tall"									"50"
			"Visible"								"1"
			"Enabled"								"1"
		}
		"BlueTeamScoreDropshadow"
		{
			"ControlName"							"CExLabel"
			"FieldName"								"BlueTeamScoreDropshadow"
			"Font"									"m0refont36"
			"FGColor"								"Black"
			"LabelText"								"%blueteamscore%"
			"TextAlignment"							"east"
			"XPos"									"81"
			"YPos"									"1"
			"ZPos"									"3"
			"Wide"									"100"
			"Tall"									"50"
			"Visible"								"1"
			"Enabled"								"1"
		}
		"BlueLeaderAvatar"
		{
			"ControlName"							"CAvatarImagePanel"
			"FieldName"								"BlueLeaderAvatar"
			"XPos"									"61"
			"YPos"									"14"
			"ZPos"									"5"
			"Wide"									"40"
			"Tall"									"40"
			"Visible"								"1"
			"Enabled"								"1"
			"Image"									""
			"ScaleImage"							"1"
			"color_outline"							"52 48 45 255"
		}
		"BlueLeaderAvatarBG"
		{
			"ControlName"							"EditablePanel"
			"FieldName"								"BlueLeaderAvatarBG"
			"XPos"									"59"
			"YPos"									"12"
			"ZPos"									"4"
			"Wide"									"44"
			"Tall"									"44"
			"Visible"								"1"
			"PaintBackgroundType"					"2"
			"BGColor_Override"						"117 107 94 255"
		}
		"RedTeamLabel"
		{
			"ControlName"							"CExLabel"
			"FieldName"								"RedTeamLabel"
			"Font"									"m0refont11"
			"LabelText"								"%redteamname%"
			"TextAlignment"							"east"
			"XPos"									"224"
			"YPos"									"25"
			"ZPos"									"10"
			"Wide"									"100"
			"Tall"									"20"
			"Visible"								"1"
			"Enabled"								"1"
			"FGColor"								"TanLight"
		}
		"RedTeamScore"
		{
			"ControlName"							"CExLabel"
			"FieldName"								"RedTeamScore"
			"Font"									"m0refont36"
			"LabelText"								"%redteamscore%"
			"TextAlignment"							"west"
			"XPos"									"202"
			"YPos"									"0"
			"ZPos"									"3"
			"Wide"									"100"
			"Tall"									"50"
			"Visible"								"1"
			"Enabled"								"1"
		}
		"RedTeamScoreDropshadow"
		{
			"ControlName"							"CExLabel"
			"FieldName"								"RedTeamScoreDropshadow"
			"Font"									"m0refont36"
			"FGColor"								"Black"
			"LabelText"								"%redteamscore%"
			"TextAlignment"							"west"
			"XPos"									"203"
			"YPos"									"1"
			"ZPos"									"3"
			"Wide"									"100"
			"Tall"									"50"
			"Visible"								"1"
			"Enabled"								"1"
		}
		"RedLeaderAvatar"
		{
			"ControlName"							"CAvatarImagePanel"
			"FieldName"								"RedLeaderAvatar"
			"XPos"									"280"
			"YPos"									"14"
			"ZPos"									"5"
			"Wide"									"40"
			"Tall"									"40"
			"Visible"								"1"
			"Enabled"								"1"
			"Image"									""
			"ScaleImage"							"1"
			"color_outline"							"52 48 45 255"
		}
		"RedLeaderAvatarBG"
		{
			"ControlName"							"EditablePanel"
			"FieldName"								"RedLeaderAvatarBG"
			"XPos"									"278"
			"YPos"									"12"
			"ZPos"									"4"
			"Wide"									"44"
			"Tall"									"44"
			"Visible"								"1"
			"PaintBackgroundType"					"2"
			"BGColor_Override"						"117 107 94 255"
		}
	}

	//==================================================================================================================================================
	// BOTTOM BAR ANCHOR
	// Moves the top bar which features the blue and red backgrounds and scores
	//==================================================================================================================================================
	"ShadedBar"
	{
		"ControlName"								"ImagePanel"
		"FieldName"									"ShadedBar"
		"XPos"										"cs-33.5"
		"YPos"										"450"
		"ZPos"										"2"
		"Wide"										"67"
		"Tall"										"125"
		"Visible"									"1"
		"Enabled"									"1"
		"PaintBackground"							"1"
		"PaintBackgroundType"						"0"
		"BGColor_Override"							"0 0 0 150"
	}
	//==================================================================================================================================================
	"WinningTeamLabel"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"WinningTeamLabel"
		"Font"										"m0refont18"
		"XPos"										"cs-33.5"
		"YPos"										"72"
		"ZPos"										"1"
		"Wide"										"67"
		"Tall"										"24"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									"%WinningTeamLabel%"
		"TextAlignment"								"center"
	}
	"WinningTeamLabelDropshadow"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"WinningTeamLabelDropshadow"
		"Font"										"m0refont18"
		"FGColor"									"Black"
		"XPos"										"cs-32.5"
		"YPos"										"73"
		"ZPos"										"1"
		"Wide"										"67"
		"Tall"										"24"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									"%WinningTeamLabel%"
		"TextAlignment"								"center"
	}
	"AdvancingTeamLabel"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"AdvancingTeamLabel"
		"Font"										"m0refont18"
		"XPos"										"cs-33.5"
		"YPos"										"72"
		"ZPos"										"1"
		"Wide"										"67"
		"Tall"										"24"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									"%AdvancingTeamLabel%"
		"TextAlignment"								"center"
	}
	"AdvancingTeamLabelDropshadow"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"AdvancingTeamLabelDropshadow"
		"Font"										"m0refont18"
		"FGColor"									"Black"
		"XPos"										"cs-32.5"
		"YPos"										"73"
		"ZPos"										"1"
		"Wide"										"67"
		"Tall"										"24"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									"%AdvancingTeamLabel%"
		"TextAlignment"								"center"
	}

	//==================================================================================================================================================
	// PLAYER ONE
	//==================================================================================================================================================
	"Player1Score"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"Player1Score"
		"Font"										"m0refont11"
		"XPos"										"60"
		"YPos"										"132"
		"ZPos"										"3"
		"Wide"										"7"
		"Tall"										"20"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									""
		"TextAlignment"								"east"
	}
	"Player1Avatar"
	{
		"ControlName"								"CAvatarImagePanel"
		"FieldName"									"Player1Avatar"
		"XPos"										"9"
		"YPos"										"135"
		"ZPos"										"3"
		"Wide"										"3"
		"Tall"										"14"
		"Visible"									"1"
		"Enabled"									"1"
		"Image"										""
		"ScaleImage"								"1"
		"color_outline"								"52 48 45 255"
	}
	"Player1Name"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"Player1Name"
		"Font"										"m0refont11"
		"XPos"										"14"
		"YPos"										"132"
		"ZPos"										"3"
		"Wide"										"31"
		"Tall"										"20"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									""
		"TextAlignment"								"west"
	}
	"Player1Class"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"Player1Class"
		"Font"										"m0refont11"
		"XPos"										"45"
		"YPos"										"132"
		"ZPos"										"3"
		"Wide"										"50"
		"Tall"										"20"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									""
		"TextAlignment"								"west"
	}
	"Player1Badge"
	{
		"ControlName"								"CTFBadgePanel"
		"FieldName"									"Player1Badge"
		"XPos"										"2"
		"YPos"										"130"
		"ZPos"										"3"
		"Wide"										"6"
		"Tall"										"25"
		"Visible"									"0"
		"Enabled"									"1"
	}

	//==================================================================================================================================================
	// PLAYER TWO
	//==================================================================================================================================================
	"Player2Score"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"Player2Score"
		"Font"										"m0refont11"
		"XPos"										"60"
		"YPos"										"152"
		"ZPos"										"3"
		"Wide"										"7"
		"Tall"										"20"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									""
		"TextAlignment"								"east"
	}
	"Player2Avatar"
	{
		"ControlName"								"CAvatarImagePanel"
		"FieldName"									"Player2Avatar"
		"XPos"										"9"
		"YPos"										"155"
		"ZPos"										"3"
		"Wide"										"3"
		"Tall"										"14"
		"Visible"									"1"
		"Enabled"									"1"
		"Image"										""
		"ScaleImage"								"1"
		"color_outline"								"52 48 45 255"
	}
	"Player2Name"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"Player2Name"
		"Font"										"m0refont11"
		"XPos"										"14"
		"YPos"										"152"
		"ZPos"										"3"
		"Wide"										"31"
		"Tall"										"20"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									""
		"TextAlignment"								"west"
	}
	"Player2Class"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"Player2Class"
		"Font"										"m0refont11"
		"XPos"										"45"
		"YPos"										"152"
		"ZPos"										"3"
		"Wide"										"50"
		"Tall"										"20"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									""
		"TextAlignment"								"west"
	}
	"Player2Badge"
	{
		"ControlName"								"CTFBadgePanel"
		"FieldName"									"Player2Badge"
		"XPos"										"2"
		"YPos"										"150"
		"ZPos"										"3"
		"Wide"										"6"
		"Tall"										"25"
		"Visible"									"0"
		"Enabled"									"1"
	}

	//==================================================================================================================================================
	// PLAYER THREE
	//==================================================================================================================================================
	"Player3Score"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"Player3Score"
		"Font"										"m0refont11"
		"XPos"										"60"
		"YPos"										"172"
		"ZPos"										"3"
		"Wide"										"7"
		"Tall"										"20"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									""
		"TextAlignment"								"east"
	}
	"Player3Avatar"
	{
		"ControlName"								"CAvatarImagePanel"
		"FieldName"									"Player3Avatar"
		"XPos"										"9"
		"YPos"										"175"
		"ZPos"										"3"
		"Wide"										"3"
		"Tall"										"14"
		"Visible"									"1"
		"Enabled"									"1"
		"Image"										""
		"ScaleImage"								"1"
		"color_outline"								"52 48 45 255"
	}
	"Player3Name"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"Player3Name"
		"Font"										"m0refont11"
		"XPos"										"14"
		"YPos"										"172"
		"ZPos"										"3"
		"Wide"										"31"
		"Tall"										"20"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									""
		"TextAlignment"								"west"
	}
	"Player3Class"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"Player3Class"
		"Font"										"m0refont11"
		"XPos"										"45"
		"YPos"										"172"
		"ZPos"										"3"
		"Wide"										"50"
		"Tall"										"20"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									""
		"TextAlignment"								"west"
	}
	"Player3Badge"
	{
		"ControlName"								"CTFBadgePanel"
		"FieldName"									"Player3Badge"
		"XPos"										"2"
		"YPos"										"170"
		"ZPos"										"3"
		"Wide"										"6"
		"Tall"										"25"
		"Visible"									"0"
		"Enabled"									"1"
	}



	//==================================================================================================================================================
	// REMOVED ELEMENTS
	//==================================================================================================================================================

	"WinPanelBGBorder"
	{
		"ControlName"								"EditablePanel"
		"FieldName"									"WinPanelBGBorder"
		"XPos"										"cs-0.5"
		"YPos"										"70"
		"ZPos"										"0"
		"Wide"										"p0.94"
		"Tall"										"185"
		"Visible"									"1"
		"Enabled"									"1"
		"ProportionalToParent"						"1"
	}
	"WinReasonLabel"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"WinReasonLabel"
		"Font"										"m0refont11"
		"XPos"										"cs-33.5"
		"YPos"										"89"
		"ZPos"										"1"
		"Wide"										"67"
		"Tall"										"30"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									"%WinReasonLabel%"
		"CenterWrap"								"1"
	}
	"DetailsLabel"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"DetailsLabel"
		"Font"										"m0refont11"
		"XPos"										"cs-33.5"
		"YPos"										"101"
		"ZPos"										"1"
		"Wide"										"67"
		"Tall"										"20"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									"%DetailsLabel%"
		"TextAlignment"								"center"
	}
	"TopPlayersLabel"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"TopPlayersLabel"
		"Font"										"m0refont11"
		"XPos"										"4"
		"YPos"										"114"
		"ZPos"										"3"
		"Wide"										"50"
		"Tall"										"20"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									"%TopPlayersLabel%"
		"TextAlignment"								"west"
	}
	"PointsThisRoundLabel"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"PointsThisRoundLabel"
		"Font"										"m0refont11"
		"XPos"										"35"
		"YPos"										"114"
		"ZPos"										"3"
		"Wide"										"35"
		"Tall"										"20"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									"#Winpanel_PointsThisRound"
		"TextAlignment"								"east"
	}
	"HorizontalLine"
	{
		"ControlName"								"ImagePanel"
		"FieldName"									"HorizontalLine"
		"XPos"										"4"
		"YPos"										"129"
		"ZPos"										"3"
		"Wide"										"65"
		"Tall"										"1"
		"Visible"									"1"
		"Enabled"									"1"
		"PaintBackground"							"1"
		"PaintBackgroundType"						"0"
		"BGColor_Override"							"250 234 201 255"
	}
	"KillStreakLeaderLabel"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"KillStreakLeaderLabel"
		"Font"										"m0refont11"
		"XPos"										"4"
		"YPos"										"200"
		"ZPos"										"3"
		"Wide"										"65"
		"Tall"										"20"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									"%KillStreakLeaderLabel%"
		"TextAlignment"								"west"
	}
	"KillStreakMaxCountLabel"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"KillStreakMaxCountLabel"
		"Font"										"m0refont11"
		"XPos"										"4"
		"YPos"										"214"
		"ZPos"										"3"
		"Wide"										"65"
		"Tall"										"20"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									"%KillStreakMaxCountLabel%"
		"TextAlignment"								"west"
	}
	"HorizontalLine2"
	{
		"ControlName"								"ImagePanel"
		"FieldName"									"HorizontalLine2"
		"XPos"										"4"
		"YPos"										"194"
		"ZPos"										"3"
		"Wide"										"65"
		"Tall"										"1"
		"Visible"									"1"
		"Enabled"									"1"
		"PaintBackground"							"1"
		"PaintBackgroundType"						"0"
		"BGColor_Override"							"250 234 201 255"
	}
	"KillStreakPlayer1Badge"
	{
		"ControlName"								"CTFBadgePanel"
		"FieldName"									"KillStreakPlayer1Badge"
		"XPos"										"2"
		"YPos"										"210"
		"ZPos"										"3"
		"Wide"										"6"
		"Tall"										"25"
		"Visible"									"0"
		"Enabled"									"1"
	}
	"KillStreakPlayer1Avatar"
	{
		"ControlName"								"CAvatarImagePanel"
		"FieldName"									"KillStreakPlayer1Avatar"
		"XPos"										"9"
		"YPos"										"215"
		"ZPos"										"3"
		"Wide"										"3"
		"Tall"										"14"
		"Visible"									"1"
		"Enabled"									"1"
		"Image"										""
		"ScaleImage"								"1"
		"color_outline"								"52 48 45 255"
	}
	"KillStreakPlayer1Name"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"KillStreakPlayer1Name"
		"Font"										"m0refont11"
		"XPos"										"14"
		"YPos"										"212"
		"ZPos"										"3"
		"Wide"										"31"
		"Tall"										"20"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									""
		"TextAlignment"								"west"
	}
	"KillStreakPlayer1Class"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"KillStreakPlayer1Class"
		"Font"										"m0refont11"
		"XPos"										"45"
		"YPos"										"212"
		"ZPos"										"3"
		"Wide"										"50"
		"Tall"										"20"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									""
		"TextAlignment"								"west"
	}
	"KillStreakPlayer1Score"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"KillStreakPlayer1Score"
		"Font"										"m0refont11"
		"XPos"										"60"
		"YPos"										"212"
		"ZPos"										"3"
		"Wide"										"7"
		"Tall"										"20"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									""
		"TextAlignment"								"east"
	}
}